name: C/C++ CI

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}-build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows",
            os: windows-latest,
            artifact: "windows.7z",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            generators: "Visual Studio 16 2019"
          }
        - {
            name: "Ubuntu",
            os: ubuntu-latest,
            artifact: "ubuntu.7z",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }
        - {
            name: "macOS",
            os: macos-latest,
            artifact: "macos.7z",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja"
          }
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: ON
        run_tests: OFF
        unit_test_build: -Dtest=OFF
    - uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r ${{matrix.config.artifact}}.zip .